# Generated by Django 5.2.14 on 2026-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
