# Generated by Django 5.2.14 on 2026-05-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_name",
                    models.CharField(max_length=150, verbose_name="Part Name"),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit or OEM part number (e.g. BP-F-10293)",
                        max_length=100,
                        unique=True,
                        verbose_name="SKU / OEM Number",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("braking", "Braking System"),
                            ("engine", "Engine Components"),
                            ("suspension", "Suspension"),
                            ("electrical", "Electrical"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("bosch", "Bosch"),
                            ("kbx", "KBX"),
                            ("mann_filter", "MANN-FILTER"),
                            ("exide", "Exide"),
                            ("minda", "Minda"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "initial_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Initial Stock"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="A warning is triggered when stock falls below this value.",
                        verbose_name="Low Stock Threshold",
                    ),
                ),
                (
                    "aisle_location",
                    models.CharField(
                        blank=True,
                        help_text="Rack / Shelf aisle identifier (e.g. A3)",
                        max_length=20,
                        verbose_name="Aisle",
                    ),
                ),
                (
                    "bin_location",
                    models.CharField(
                        blank=True,
                        help_text="Bin identifier within the aisle (e.g. B12)",
                        max_length=20,
                        verbose_name="Bin",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Wholesale Price (Cost)",
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Retail Price",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=False, verbose_name="Item is Taxable (GST applies)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inventory/images/",
                        verbose_name="Part Image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active")],
                        default="draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        choices=[
                            ("toyota", "Toyota"),
                            ("honda", "Honda"),
                            ("maruti_suzuki", "Maruti Suzuki"),
                            ("hyundai", "Hyundai"),
                            ("kia", "Kia"),
                            ("mahindra", "Mahindra"),
                            ("tata", "Tata"),
                            ("mg", "MG"),
                            ("volkswagen", "Volkswagen"),
                            ("skoda", "Skoda"),
                            ("Renault", "Renault"),
                            ("nissan", "Nissan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Make",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g. Camry", max_length=100, verbose_name="Model"
                    ),
                ),
                (
                    "year_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 2018-2022",
                        max_length=20,
                        verbose_name="Year Range",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_compatibilities",
                        to="inventory.inventory",
                        verbose_name="Inventory Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Compatibility",
                "verbose_name_plural": "Vehicle Compatibilities",
            },
        ),
    ]
