# Generated by Django 5.2.14 on 2026-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_phone_number",
            field=models.IntegerField(),
        ),
    ]
